# Generated by Django 5.0.1 on 2024-01-10 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dropdownlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropdownlist_name', models.CharField(help_text='下拉選單名稱', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='select_option',
            name='text',
            field=models.CharField(help_text='下拉選項名稱', max_length=100),
        ),
        migrations.AlterField(
            model_name='select_option',
            name='value',
            field=models.IntegerField(help_text='下拉選項編號'),
        ),
        migrations.AddField(
            model_name='select_option',
            name='dropdownlist_name',
            field=models.ForeignKey(help_text='下拉選單名稱', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.dropdownlist'),
        ),
    ]
