# Generated by Django 5.0.1 on 2024-01-10 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_dropdownlist_alter_select_option_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_code', models.CharField(max_length=10)),
                ('avg_closing_price', models.FloatField(null=True)),
                ('avg_volume', models.FloatField(null=True)),
                ('latest_date', models.DateTimeField(null=True)),
                ('latest_closing_price', models.FloatField(null=True)),
                ('previous_date', models.DateTimeField(null=True)),
                ('previous_closing_price', models.FloatField(null=True)),
                ('closing_price_percentage_diff', models.FloatField(null=True)),
                ('latest_volume', models.FloatField(null=True)),
                ('previous_volume', models.FloatField(null=True)),
                ('volume_percentage_diff', models.FloatField(null=True)),
                ('company_type', models.CharField(max_length=10, null=True)),
                ('max_closing_price', models.FloatField(null=True)),
                ('max_volume', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'filter_3',
                'managed': False,
            },
        ),
    ]
